apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certificates
  namespace: FreeTheIdServer
spec:
  accessModes:
  - ReadOnlyMany
  volumeMode: Filesystem
  resources:
   requests:
    storage: 10Mi