kind: Secret
apiVersion: v1
metadata:
  name: FreeTheIdServer-private-secrets
  namespace: FreeTheIdServer
data:
  protect-key: UEBzc3cwcmQ= # replace by your base64 encoded password for FreeTheIdServer.pfx
  tls.pwd: UEBzc3cwcmQ= # replace by your base64 encoded password for tls-private.pfx
