<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<UserSecretsId>51a7f0be-96e4-42d5-ad09-37e9adabfff6</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..</DockerfileContext>

		<EnablePreviewFeatures>True</EnablePreviewFeatures>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DefineConstants>$(DefineConstants)TRACE</DefineConstants>
		<NoWarn>1701;1702;NU1603</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DefineConstants>$(DefineConstants)TRACE</DefineConstants>
		<NoWarn>1701;1702;NU1603</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="Localization-fr.json" />
		<Content Remove="Localization-de.json" />
		<Content Remove="Localization-hi.json" />
	</ItemGroup>

	<ItemGroup>
		<None Include="Localization-fr.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Include="Localization-de.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Include="Localization-hi.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Aguacongas.FreeTheIdServer.BlazorApp\Aguacongas.FreeTheIdServer.BlazorApp.csproj" />
		<ProjectReference Include="..\Aguacongas.FreeTheIdServer\Aguacongas.FreeTheIdServer.csproj" />
		<ProjectReference Include="..\IdentityServer\Aguacongas.Open.IdentityServer.Admin\Aguacongas.Open.IdentityServer.Admin.csproj" />
		<ProjectReference Include="..\IdentityServer\Open\Aguacongas.Open.IdentityServer.Admin.Open\Aguacongas.Open.IdentityServer.Admin.Open.csproj" />
		<ProjectReference Include="..\IdentityServer\Open\Aguacongas.Open.IdentityServer.EntityFramework.Store.Open\Aguacongas.Open.IdentityServer.EntityFramework.Store.Open.csproj" />
		<ProjectReference Include="..\IdentityServer\Open\Aguacongas.Open.IdentityServer.KeysRotation.Open\Aguacongas.Open.IdentityServer.KeysRotation.Open.csproj" />
		<ProjectReference Include="..\IdentityServer\Open\Aguacongas.Open.IdentityServer.MongoDb.Store.Open\Aguacongas.Open.IdentityServer.MongoDb.Store.Open.csproj" />
		<ProjectReference Include="..\IdentityServer\Open\Aguacongas.Open.IdentityServer.RavenDb.Store.Open\Aguacongas.Open.IdentityServer.RavenDb.Store.Open.csproj" />
		<ProjectReference Include="..\IdentityServer\Open\Aguacongas.Open.IdentityServer.Saml2p.Open\Aguacongas.Open.IdentityServer.Saml2p.Open.csproj" />
		<ProjectReference Include="..\IdentityServer\Open\Aguacongas.Open.IdentityServer.WsFederation.Open\Aguacongas.Open.IdentityServer.WsFederation.Open.csproj" />
		<ProjectReference Include="..\Identity\Aguacongas.FreeTheIdServer.Identity.Argon2PasswordHasher\Aguacongas.FreeTheIdServer.Identity.Argon2PasswordHasher.csproj" />
		<ProjectReference Include="..\Identity\Aguacongas.FreeTheIdServer.Identity.BcryptPasswordHasher\Aguacongas.FreeTheIdServer.Identity.BcryptPasswordHasher.csproj" />
		<ProjectReference Include="..\Identity\Aguacongas.FreeTheIdServer.Identity.ScryptPasswordHasher\Aguacongas.FreeTheIdServer.Identity.ScryptPasswordHasher.csproj" />
		<ProjectReference Include="..\Identity\Aguacongas.FreeTheIdServer.Identity.UpgradePasswordHasher\Aguacongas.FreeTheIdServer.Identity.UpgradePasswordHasher.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Duende.AspNetCore.Authentication.OAuth2Introspection" Version="7.0.1" />
		<PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="10.0.11" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
	</ItemGroup>
</Project>
