<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
    <EnablePreviewFeatures>True</EnablePreviewFeatures>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
		<PackageReference Include="xunit" Version="2.9.3" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="coverlet.collector" Version="10.0.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Extensions\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\src\Aguacongas.FreeTheIdServer.Authentication\Aguacongas.FreeTheIdServer.Authentication.csproj" />
	  <ProjectReference Include="..\..\..\src\Aguacongas.FreeTheIdServer.Identity\Aguacongas.FreeTheIdServer.Identity.csproj" />
	  <ProjectReference Include="..\..\..\src\IdentityServer\Aguacongas.Open.IdentityServer.Http.Store\Aguacongas.Open.IdentityServer.Http.Store.csproj" />
	  <ProjectReference Include="..\..\..\src\IdentityServer\Open\Aguacongas.Open.IdentityServer.Open\Aguacongas.Open.IdentityServer.Open.csproj" />
	</ItemGroup>

</Project>

